name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.ivy2/cache
          key: ${{ runner.os }}-build-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.8
      - run: sbt publishLocal
      - uses: actions/upload-artifact@v2
        with:
          name: protoc-jar-aarch64
          path: /home/runner/.ivy2/local
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'azolotko/protoc-jar-aarch64' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') )
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
            ~/.ivy2/cache
          key: ${{ runner.os }}-publish-cache-${{ hashFiles('*.sbt') }}-${{ hashFiles('project/*') }}
      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.8
      - run: sbt publishSigned
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      - if: startsWith(github.ref, 'refs/tags/')
        run: sbt sonatypeBundleRelease
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
